name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: maneki:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t docker.pkg.github.com/masterwok/maneki-backend/${{ env.IMAGE_TAG }} .
        docker push docker.pkg.github.com/masterwok/maneki-backend/${{ env.IMAGE_TAG }}
        
    - name: Load Docker image on Synology NAS
      run: |
        sshpass -p "${{ secrets.SYNOLOGY_PASSWORD }}" ssh -p 2222 ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} "docker pull docker.pkg.github.com/masterwok/maneki-dev/${{ env.IMAGE_TAG }}"
        sshpass -p "${{ secrets.SYNOLOGY_PASSWORD }}" ssh -p 2222 ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} "docker tag docker.pkg.github.com/masterwok/maneki-dev/${{ env.IMAGE_TAG }} ${{ env.IMAGE_TAG }}"
        sshpass -p "${{ secrets.SYNOLOGY_PASSWORD }}" ssh -p 2222 ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} "docker rm -f maneki || true"
        sshpass -p "${{ secrets.SYNOLOGY_PASSWORD }}" ssh -p 2222 ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} "docker run -d -p <port>:<port> --name=maneki -e ENV_VAR1=value1 -e ENV_VAR2=value2 ${{ env.IMAGE_TAG }}"


   
