name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: docker build -t maneki .

    - name: Tag Docker image
      run: docker tag maneki ${{ secrets.REGISTRY_USERNAME }}/maneki:${{ github.sha }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.REGISTRY_USERNAME }}/maneki:latest
          ${{ secrets.REGISTRY_PASSWORD }}/maneki:${{ github.sha }}

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client


