name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.repository }}:${{ github.sha }}
  APP_NAME: maneki

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.IMAGE_TAG }}

    - name: Load Docker image on Synology NAS
      uses: matheusvanzan/sshpass-action@v2
      with:
        port: 2222
        user: ${{ secrets.SYNOLOGY_USERNAME }}
        host: ${{ secrets.SYNOLOGY_HOST }}
        pass: ${{ secrets.SYNOLOGY_PASSWORD }}  
        run: |
          export PATH="$PATH:/usr/local/bin"
          
          echo "Logging into ghcr.io"
          echo "${{ secrets.GITHUB_TOKEN }}" |  docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          echo "Pulling docker container ghcr.io/${{ env.IMAGE_TAG }}"
          docker pull ghcr.io/${{ env.IMAGE_TAG }}
          
          echo "Stop running container"
          docker stop ${{ env.APP_NAME }} || true

          echo "Remove old container"
          docker rm ${{ env.APP_NAME }} || true

          echo "Run new container"
          docker run \
            -d \
            --name="${{ env.APP_NAME }}" \
            --restart=on-failure:3 \
            --log-opt max-size=5m \
            --log-opt max-file=3 \
            -p ${{ env.PORT }}:${{ env.PORT }} \
            -e JDBC_URL="${{ secrets.JDBC_URL }}" \
            -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            -e MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            -e MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            ghcr.io/${{ env.IMAGE_TAG }}
      
