name: Deploy to Synology NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Tag Docker image
      run: docker tag myapp ${DOCKER_USERNAME}/myapp:${{ github.sha }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${DOCKER_USERNAME}/myapp:latest
          ${DOCKER_USERNAME}/myapp:${{ github.sha }}

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Deploy to Synology NAS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SYNOLOGY_HOST }}
        username: ${{ secrets.SYNOLOGY_USERNAME }}
        password: ${{ secrets.SYNOLOGY_PASSWORD }}
        source: "${{ github.workspace }}/docker-compose.yml"
        target: "/volume1/docker/myapp/docker-compose.yml"
